spring:
  application:
    # 服务名
    name: business-transaction
  cloud:
    nacos:
      discovery:
        # 服务注册中心
        server-addr: 120.79.0.210:8848

server:
  port: 13000

management:
  endpoints:
    web:
      exposure:
        include: "*"
