spring:
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.0.210:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 这里使用的是 ip:3336/db_order 的数据库（一个服务一个数据库）
    url: jdbc:mysql://192.168.8.50:3306/dehua?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

server:
  port: 11000


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.laoshiren.hello.seata.http.domain.domain

logging:
  level:
    com.laoshiren.hello.seata.http.mapper: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"