spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: business-transaction
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.0.210:8848
  alibaba:
    seata:
      tx-service-group: tx-group

dubbo:
  scan:
    base-packages: com.laoshiren.hello.seata.bbbusiness.transaction.controller
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://120.79.0.210:8848

server:
  port: 27010

management:
  endpoints:
    web:
      exposure:
        include: "*"